### ISSUE TITLE
Python error "RecursionError"

### ISSUE THREAD

**Issue by Gustry** [wonder-sk/qgis-first-aid-plugin#44]
I have the latest version of the plugin, and I have this error in my Python console :

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 190, in qgis_excepthook
    showException(type, value, tb, None, messagebar=in_main_thread)
  File "/home/etienne/.local/share/QGIS/QGIS3/profiles/wpd/python/plugins/firstaid/__init__.py", line 62, in showException
    show_debug_widget((etype, value, tb))
  File "/home/etienne/.local/share/QGIS/QGIS3/profiles/wpd/python/plugins/firstaid/__init__.py", line 35, in show_debug_widget
    dw = DebugDialog(debug_widget_data)
RecursionError: maximum recursion depth exceeded
```

I would need to dig about the actual dev I'm doing.

**Comment by nyalldawson** [comment]
@Gustry is this still an issue?

**Comment by Gustry** [comment]
I don't think so. I will reopen if necessary.
